### ISSUE TITLE
Filter input file types

### ISSUE THREAD

**Issue by jjliston** [christo-ph/mkdocs_build_plantuml#7]
It would be convenient to store the Markdown and PlantUML source files in the same folders. This makes it easier to keep track of related files, especially in large projects, and to link to the generated SVG files.

For example...
```
/project
    /docs
        /topic1
            document1.md
            document2.md
            diagram1.puml
            diagram1.svg    <== generated
        /topic2
            document1.md
            document2.md
            diagram1.puml
            diagram1.svg    <== generated
```

I tried implementing this by configuring the plugin as so...
```
plugins:
  - search
  - build_plantuml:
      diagram_root: "docs"
      output_folder: ""
      input_folder: ""
```
This works but with one major drawback. The plugin sends ALL file types to the PlantUML server. It successfully converts `.puml` files to `.svg` but throws errors when processing `.md` or other file types.

Would it be possible to have the plugin scan only `.puml` files? Maybe this could/should be configurable.
