### ISSUE TITLE
SVG or PNG being generated, but not moved to the "source" folder.

### ISSUE THREAD

**Issue by GAS85** [christo-ph/mkdocs_build_plantuml#9]
Hello,

I do use your plugin and seems my diagrams generated and saved in a "out" folder. Unfortunately I can't find them in the mkdocs output folder.
My config.
```
theme:
  # The string name of a known installed theme
  name: 'material'

# The directory where the output HTML and other files are created
site_dir: source

plugins:
  # built-in MkDocs search plugin
  - search
  # helps building plantuml images
  - build_plantuml:
      render: "local"
      bin_path: "/usr/bin/plantuml"
      output_format: "svg"
      diagram_root: "docs/diagrams"
      output_folder: "out"
      input_folder: "src"
```
My input folders:
```
ls -laR
...
./docs/diagrams:
total 16
drwxrwxrwx    4 root     root          4096 Mar 26 08:24 .
drwxrwxrwx    9 root     root          4096 Mar 26 08:24 ..
drwxr-xr-x    2 root     root          4096 Mar 26 08:24 out
drwxrwxrwx    2 root     root          4096 Mar 26 08:24 src
./docs/diagrams/out:
total 52
drwxr-xr-x    2 root     root          4096 Mar 26 08:24 .
drwxrwxrwx    4 root     root          4096 Mar 26 08:24 ..
-rw-r--r--    1 root     root         43218 Mar 26 08:24 system_quick_overview.svg
./docs/diagrams/src:
total 12
drwxrwxrwx    2 root     root          4096 Mar 26 08:24 .
drwxrwxrwx    4 root     root          4096 Mar 26 08:24 ..
-rw-rw-rw-    1 root     root           475 Mar 26 08:24 system_quick_overview.puml
```
My mkdocs output folder:
```
./source/diagrams:
total 12
drwxr-xr-x    3 root     root          4096 Mar 26 08:24 .
drwxr-xr-x   11 root     root          4096 Mar 26 08:24 ..
drwxr-xr-x    2 root     root          4096 Mar 26 08:24 src
./source/diagrams/src:
total 12
drwxr-xr-x    2 root     root          4096 Mar 26 08:24 .
drwxr-xr-x    3 root     root          4096 Mar 26 08:24 ..
-rw-r--r--    1 root     root           475 Mar 26 08:24 system_quick_overview.puml
```
Do you have any advice why `out` from input folder (`docs`) is not moved to the output folder `source`?
